import {
    Employee,
    Meeting,
    ProductArea,
    Product,
    Sale,
    Delivery,
    User,
} from "@/app/utils/definitions";

export const employees: Employee[] = [
    {
        name: "Jorge Rodríguez",
        phone: "+54 11 4567-8901",
        area: "Cajas",
        photo_url: "https://i.ibb.co/35t9Mz5N/Jorge.png",
        salary: 450000,
        genre: "M",
    },
    {
        name: "Lucía Fernández",
        phone: "+54 11 2345-6789",
        area: "Fiambrería",
        photo_url: "https://randomuser.me/api/portraits/women/2.jpg",
        salary: 480000,
        genre: "F",
    },
    {
        name: "Marcos Galperin",
        phone: "+54 11 9876-5432",
        area: "Depósito",
        photo_url: "https://randomuser.me/api/portraits/men/3.jpg",
        salary: 420000,
        genre: "M",
    },
    {
        name: "Valeria Gómez",
        phone: "+54 11 5555-4444",
        area: "Administración",
        photo_url: "https://randomuser.me/api/portraits/women/4.jpg",
        salary: 600000,
        genre: "F",
    },
    {
        name: "Martín Sosa",
        phone: "+54 11 3333-2222",
        area: "Verdulería",
        photo_url: "https://randomuser.me/api/portraits/men/5.jpg",
        salary: 440000,
        genre: "M",
    },
    {
        name: "Elena Ruiz",
        phone: "+54 11 6666-7777",
        area: "Limpieza",
        photo_url: "https://randomuser.me/api/portraits/women/6.jpg",
        salary: 400000,
        genre: "F",
    },
    {
        name: "Roberto Díaz",
        phone: "+54 11 1122-3344",
        area: "Carnicería",
        photo_url: "https://randomuser.me/api/portraits/men/7.jpg",
        salary: 520000,
        genre: "M",
    },
    {
        name: "Sofía Martínez",
        phone: "+54 11 9988-7766",
        area: "Panadería",
        photo_url: "https://randomuser.me/api/portraits/women/8.jpg",
        salary: 490000,
        genre: "F",
    },
    {
        name: "Jorge Romero",
        phone: "+54 11 5566-7788",
        area: "Seguridad",
        photo_url: "https://randomuser.me/api/portraits/men/9.jpg",
        salary: 430000,
        genre: "M",
    },
    {
        name: "Valentina López",
        phone: "+54 11 4433-2211",
        area: "Cajas",
        photo_url: "https://randomuser.me/api/portraits/women/10.jpg",
        salary: 450000,
        genre: "F",
    },
    {
        name: "Lucas Méndez",
        phone: "+54 11 6655-4433",
        area: "Reposición",
        photo_url: "https://randomuser.me/api/portraits/men/11.jpg",
        salary: 410000,
        genre: "M",
    },
    {
        name: "Patricia Vega",
        phone: "+54 11 7788-9900",
        area: "Gerencia",
        photo_url: "https://randomuser.me/api/portraits/women/12.jpg",
        salary: 950000,
        genre: "F",
    },
    {
        name: "Fernando Torres",
        phone: "+54 11 1231-2312",
        area: "Depósito",
        photo_url: "https://randomuser.me/api/portraits/men/13.jpg",
        salary: 425000,
        genre: "M",
    },
    {
        name: "Camila Ocampo",
        phone: "+54 11 8989-1212",
        area: "Recursos Humanos",
        photo_url: "https://randomuser.me/api/portraits/women/14.jpg",
        salary: 620000,
        genre: "F",
    },
    {
        name: "Ricardo Alarcón",
        phone: "+54 11 4545-6767",
        area: "Carnicería",
        photo_url: "https://randomuser.me/api/portraits/men/15.jpg",
        salary: 510000,
        genre: "M",
    },
    {
        name: "Marina Duarte",
        phone: "+54 11 2323-4545",
        area: "Panadería",
        photo_url: "https://randomuser.me/api/portraits/women/16.jpg",
        salary: 485000,
        genre: "F",
    },
    {
        name: "Gustavo Silva",
        phone: "+54 11 6767-8989",
        area: "Mantenimiento",
        photo_url: "https://randomuser.me/api/portraits/men/17.jpg",
        salary: 460000,
        genre: "M",
    },
    {
        name: "Ana Clara Rossi",
        phone: "+54 11 9090-1212",
        area: "Marketing",
        photo_url: "https://randomuser.me/api/portraits/women/18.jpg",
        salary: 580000,
        genre: "F",
    },
    {
        name: "Julián Álvarez",
        phone: "+54 11 3434-5656",
        area: "Reposición",
        photo_url: "https://randomuser.me/api/portraits/men/19.jpg",
        salary: 410000,
        genre: "M",
    },
    {
        name: "Teresa Collado",
        phone: "+54 11 7878-9090",
        area: "Limpieza",
        photo_url: "https://randomuser.me/api/portraits/women/20.jpg",
        salary: 400000,
        genre: "F",
    },
];

export const payroll = () => {
    return employees.reduce((total, em) => total + em.salary, 0);
};

export const mvpEmployee = employees.reduce((max, current) => {
    return current.salary > max.salary ? current : max;
});

export const salaryAverage = (payroll() / employees.length).toFixed(0);

export const upcomingMeetings: Meeting[] = [
    {
        employee: employees[0].name,
        day: new Date("2025-12-18"),
        hour: 9,
        minute: 30,
    },
    {
        employee: employees[1].name,
        day: new Date("2025-12-18"),
        hour: 11,
        minute: 0,
    },
    {
        employee: employees[3].name,
        day: new Date("2025-12-19"),
        hour: 14,
        minute: 15,
    },
    {
        employee: employees[2].name,
        day: new Date("2025-12-19"),
        hour: 16,
        minute: 45,
    },
    {
        employee: employees[5].name,
        day: new Date("2025-12-20"),
        hour: 10,
        minute: 0,
    },
    {
        employee: employees[7].name,
        day: new Date("2025-12-19"),
        hour: 16,
        minute: 45,
    },
    {
        employee: employees[6].name,
        day: new Date("2025-12-19"),
        hour: 16,
        minute: 45,
    },
];

export const productAreas: ProductArea[] = [
    { id: 1, name: "Perecederos" },
    { id: 2, name: "No Perecederos" },
    { id: 3, name: "Bebidas" },
    { id: 4, name: "Congelados" },
    { id: 5, name: "Cuidado Personal y Limpieza" },
    { id: 6, name: "Bazar" },
    { id: 7, name: "Otros" },
];

export const products: Product[] = [
    {
        id: 101,
        name: "Leche Entera La Serenísima 1L",
        area: productAreas[0],
        price: 1450,
        hasDiscount: false,
        discount: 0,
        stock: 45,
    },
    {
        id: 102,
        name: "Arroz Gallo Oro 1kg",
        area: productAreas[1],
        price: 1800,
        hasDiscount: true,
        discount: 15,
        stock: 120,
    },
    {
        id: 103,
        name: "Coca-Cola Sabor Original 2.25L",
        area: productAreas[2],
        price: 2900,
        hasDiscount: false,
        discount: 0,
        stock: 80,
    },
    {
        id: 104,
        name: "Hamburguesas Paty Clásicas x4",
        area: productAreas[3],
        price: 4500,
        hasDiscount: true,
        discount: 10,
        stock: 35,
    },
    {
        id: 105,
        name: "Detergente Magistral Limón 500ml",
        area: productAreas[4],
        price: 2200,
        hasDiscount: false,
        discount: 0,
        stock: 60,
    },
    {
        id: 106,
        name: "Queso Crema Casancrem 300g",
        area: productAreas[0],
        price: 3100,
        hasDiscount: true,
        discount: 5,
        stock: 25,
    },
    {
        id: 107,
        name: "Fideos Matarazzo Tirabuzón 500g",
        area: productAreas[1],
        price: 1350,
        hasDiscount: false,
        discount: 0,
        stock: 150,
    },
    {
        id: 108,
        name: "Vino Malbec Rutini 750ml",
        area: productAreas[2],
        price: 12500,
        hasDiscount: true,
        discount: 20,
        stock: 12,
    },
    {
        id: 109,
        name: "Shampoo Pantene Restauración 400ml",
        area: productAreas[4],
        price: 5800,
        hasDiscount: false,
        discount: 0,
        stock: 40,
    },
    {
        id: 110,
        name: "Set de Tuppers x3",
        area: productAreas[5],
        price: 8500,
        hasDiscount: true,
        discount: 30,
        stock: 15,
    },
    {
        id: 111,
        name: "Helado NotCream Chocolate 300g",
        area: productAreas[3],
        price: 6200,
        hasDiscount: false,
        discount: 0,
        stock: 20,
    },
    {
        id: 112,
        name: "Alimento para Perros DogChow 3kg",
        area: productAreas[6],
        price: 14000,
        hasDiscount: true,
        discount: 10,
        stock: 10,
    },
    {
        id: 113,
        name: "Pan Lactal Artesano 500g",
        area: productAreas[0],
        price: 2800,
        hasDiscount: false,
        discount: 0,
        stock: 30,
    },
    {
        id: 114,
        name: "Cerveza Patagonia Amber Lager 730ml",
        area: productAreas[2],
        price: 3600,
        hasDiscount: true,
        discount: 15,
        stock: 55,
    },
    {
        id: 115,
        name: "Papel Higiénico Higienol 80m x4",
        area: productAreas[4],
        price: 4200,
        hasDiscount: false,
        discount: 0,
        stock: 100,
    },
];

export const sales: Sale[] = [
    { product: products[0], quantity: 5 },
    { product: products[2], quantity: 12 },
    { product: products[7], quantity: 1 },
    { product: products[4], quantity: 4 },
    { product: products[14], quantity: 10 },
    { product: products[1], quantity: 20 },
];

export const deliveries: Delivery[] = [
    {
        id: 1,
        product: products[0],
        quantity: 50,
        deliveryDate: new Date("2025-12-20"),
        supplier: "Lácteos del Sur",
        status: "Entregado",
    },
    {
        id: 2,
        product: products[1],
        quantity: 100,
        deliveryDate: new Date("2025-12-21"),
        supplier: "Arrozales Argentinos",
        status: "Pendiente",
    },
    {
        id: 3,
        product: products[3],
        quantity: 40,
        deliveryDate: new Date("2025-12-22"),
        supplier: "Congelados Premium",
        status: "En tránsito",
    },
    {
        id: 4,
        product: products[8],
        quantity: 30,
        deliveryDate: new Date("2025-12-23"),
        supplier: "Higiene Total",
        status: "Entregado",
    },
    {
        id: 5,
        product: products[11],
        quantity: 20,
        deliveryDate: new Date("2025-12-24"),
        supplier: "Distribuidora Nacional",
        status: "Pendiente",
    },
    // --- Nuevos Deliveries ---
    {
        id: 6,
        product: products[2], // Coca-Cola
        quantity: 150,
        deliveryDate: new Date("2025-12-26"),
        supplier: "Bebidas del Atlántico",
        status: "En tránsito",
    },
    {
        id: 7,
        product: products[7], // Vino Malbec
        quantity: 24,
        deliveryDate: new Date("2025-12-27"),
        supplier: "Bodegas Mendocinas",
        status: "Pendiente",
    },
    {
        id: 8,
        product: products[14], // Papel Higiénico
        quantity: 200,
        deliveryDate: new Date("2025-12-15"),
        supplier: "Higiene Total",
        status: "Entregado",
    },
    {
        id: 9,
        product: products[4], // Detergente
        quantity: 80,
        deliveryDate: new Date("2025-12-28"),
        supplier: "Limpieza Express",
        status: "Pendiente",
    },
    {
        id: 10,
        product: products[6], // Fideos
        quantity: 300,
        deliveryDate: new Date("2025-12-29"),
        supplier: "Molinos del Norte",
        status: "En tránsito",
    },
    {
        id: 11,
        product: products[10], // Helado
        quantity: 60,
        deliveryDate: new Date("2025-12-30"),
        supplier: "Congelados Premium",
        status: "Pendiente",
    },
    {
        id: 12,
        product: products[13], // Cerveza Patagonia
        quantity: 120,
        deliveryDate: new Date("2025-12-18"),
        supplier: "Bebidas del Atlántico",
        status: "Entregado",
    },
    {
        id: 13,
        product: products[9], // Tuppers
        quantity: 45,
        deliveryDate: new Date("2025-12-22"),
        supplier: "Bazar Moderno",
        status: "En tránsito",
    },
    {
        id: 14,
        product: products[12], // Pan Lactal
        quantity: 90,
        deliveryDate: new Date("2025-12-20"),
        supplier: "Panificadora Central",
        status: "Entregado",
    },
    {
        id: 15,
        product: products[5], // Casancrem
        quantity: 40,
        deliveryDate: new Date("2025-12-31"),
        supplier: "Lácteos del Sur",
        status: "Pendiente",
    },
];

export const users: User[] = [
    {
        id: 1,
        email: "testUser1@gmail.com",
        name: "Usuario 1",
        password: "password123",
        role: "user",
    },
    {
        id: 2,
        email: "admin@empresa.com",
        name: "Admin Sistema",
        password: "adminSystem123",
        role: "admin",
    },
    {
        id: 3,
        email: "lucia.dev@gmail.com",
        name: "Lucía García",
        password: "securePass2024!",
        role: "user",
    },
    {
        id: 4,
        email: "m.rodriguez@tech.io",
        name: "Marcos Rodríguez",
        password: "user.9876",
        role: "user",
    },
    {
        id: 5,
        email: "super.user@admin.com",
        name: "Super Usuario",
        password: "admin_password_strong",
        role: "admin",
    }
];